### ISSUE TITLE
Not fixed

### ISSUE THREAD

**Issue by Jessica1234567891** [edgarssults/FitNote#4] opened 2020-10-05 14:01 UTC
As I said before in my issues that you closed 
The settings aren't there! 
![IMG_20201006_002922](https://user-images.githubusercontent.com/72332368/95089097-45455980-076b-11eb-9b11-5122b7f99d45.jpg)

**Comment by edgarssults** [comment] 2020-10-05 14:11
Duplicate of #3, reopened

**Closed by edgarssults** 2020-10-05 14:11 UTC
