### ISSUE TITLE
App won't sync

### ISSUE THREAD

**Issue by gamer1234coolk4** [edgarssults/FitNote#2] opened 2020-06-06 15:07 UTC
The app sync thing dosent pop up or work please fix

**Comment by edgarssults** [comment] 2020-06-07 18:41
Can you provide some steps of what you've already done in the settings screen? How far along the set up process are you?

**Comment by edgarssults** [comment] 2020-06-11 15:31
There is an update in review which might help with sync in some scenarios, but it won't fix everything.

**Comment by edgarssults** [comment] 2020-06-24 13:25
> There is an update in review which might help with sync in some scenarios, but it won't fix everything.

The new update is out, it fixes access token refresh (still manual though). Might help you, but since I don't know the error that's preventing your sync, it might not.

**Comment by edgarssults** [comment] 2020-07-12 15:47
I'm closing this since there isn't enough information provided for how to reproduce the issue.

I recommend opening the app on the watch to wake up the connection and then trying to sync if you're getting an error about sending the note to the watch.

**Closed by edgarssults** 2020-07-12 15:47 UTC

**Comment by edgarssults** [comment] 2020-09-23 09:39
I've released a new version that improves the sync process. It now syncs also when the app isn't open on the watch. That might have been your issue.
